

export const DEFAULT_SPRITE_DISPLAY_HEIGHT = 64;
export const DEFAULT_SPRITE_DISPLAY_WIDTH = 64;
export const DEFAULT_SPRITE_DISPLAY_WIDTH_2 = 65 - 35;


export const DEFAULT_RATS_DISPLAY_HEIGHT = 40;
export const DEFAULT_RATS_DISPLAY_WIDTH = 52;

export const DEFAULT_SMOKESCREEN_DISPLAY_HEIGHT = 100;
export const DEFAULT_SMOKESCREEN_DISPLAY_WIDTH = 75;

let REACT_APP_LOBBY_WEBSOCKET_SERVER = "";
console.log("REACT_APP_DEV_ENV ", process.env.REACT_APP_DEV_ENV)
if (process.env.REACT_APP_DEV_ENV === "production") {
  REACT_APP_LOBBY_WEBSOCKET_SERVER = process.env.REACT_APP_LOBBY_PROD_WEBSOCKET_SERVER ? process.env.REACT_APP_LOBBY_PROD_WEBSOCKET_SERVER: ""
} else if (process.env.REACT_APP_DEV_ENV === "development") {
  REACT_APP_LOBBY_WEBSOCKET_SERVER = process.env.REACT_APP_LOBBY_DEV_WEBSOCKET_SERVER ? process.env.REACT_APP_LOBBY_DEV_WEBSOCKET_SERVER: ""
} else if (process.env.REACT_APP_DEV_ENV === "labs") {
  REACT_APP_LOBBY_WEBSOCKET_SERVER = process.env.REACT_APP_LOBBY_LABS_WEBSOCKET_SERVER ? process.env.REACT_APP_LOBBY_LABS_WEBSOCKET_SERVER: ""
} else {
  REACT_APP_LOBBY_WEBSOCKET_SERVER = "ws://localhost:3003"
  // REACT_APP_LOBBY_WEBSOCKET_SERVER = "ws://65.1.108.101:8000/ws"
}
console.log("REACT_APP_LOBBY_WEBSOCKET_SERVER ", process.env.REACT_APP_LOBBY_WEBSOCKET_SERVER)

export default REACT_APP_LOBBY_WEBSOCKET_SERVER;